<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="button.png" />
    <None Remove="img\button.png" />
    <None Remove="img\placeholder.png" />
    <None Remove="img\scene1.jpg" />
    <None Remove="img\scene1.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />

  </ItemGroup>

  <ItemGroup>
    <Resource Include="button.png" />
    <Resource Include="img\button.png" />
    <Resource Include="img\placeholder.png" />

    <Resource Include="img\0\backdrop.png"/>

    <Resource Include="img\scene1.png">

      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
